#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gameWithCells' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER m
#




import math

def gameWithCells(n, m):
    """
    Calculate the minimum number of packages required to supply all bases on a grid.

    Parameters:
    n (int): The number of rows in the grid.
    m (int): The number of columns in the grid.

    Returns:
    int: The minimum number of packages required.
    """
    # Calculate the number of packages needed
    return math.ceil(n / 2) * math.ceil(m / 2)

# Example usage
n = 2
m = 2
print(gameWithCells(n, m))  # Output: 1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    result = gameWithCells(n, m)

    fptr.write(str(result) + '\n')

    fptr.close()
